### ISSUE TITLE
Create hard link to group

### ISSUE THREAD

**Issue by jjcasmar** [BlueBrain/HighFive#671] opened 2022-12-21 23:24 UTC
I have a group and I want to create a hard link to it. I can see there is group.createSoftLink, but I can't find anything to add a hard link. Most similar would be rename, but it doesn't allow to keep also the old name. 

Is this feature missing?

**Comment by alkino** [comment] 2023-01-23 17:07
This is a duplicate of #357 
This is a still missing feature.
If you want to give a try for adding that, feel free.

**Closed** 2023-01-23 17:08 UTC
