### ISSUE TITLE
How to read variable length arrays

### ISSUE THREAD

**Issue by WanXinTao** [BlueBrain/HighFive#439] opened 2021-04-10 11:00 UTC
I have an h5 file
```
DATASET "foo" {
    DATATYPE H5T_VLEN { H5T_STD_I32LE }
    DATASPACE SIMPLE { ( 2 ) / ( 2 ) }
    DATA {
        (0): (1), (1, 2)
    }
}
```

How should I read it, is there a similar example

**Comment by WanXinTao** [comment] 2021-04-11 08:14
@alkino I want to read the data shown in the picture above

**Comment by WanXinTao** [comment] 2021-04-11 08:15
Can you provide a demo, thank you very much

**Comment by ferdonline** [comment] 2021-09-15 11:42
AFAIK var length non-string arrays are still not supported.

**Comment by maxnoe** [comment] 2021-11-04 12:52
This is a duplicate of #369

**Comment by alkino** [comment] 2021-11-04 13:18
Thanks ;)

**Closed by alkino** 2021-11-04 13:18 UTC
Labels: question
