### ISSUE TITLE
Compound types aren't working

### ISSUE THREAD

**Issue by ChrisDeGrendele** [BlueBrain/HighFive#520] opened 2022-03-22 20:05 UTC
**Describe the bug**
Hello! 

I'm having trouble getting compound types working and then I tried running the example/compound_types.cpp and I got the same error. I'm not sure what's going on here? I only used `AtomicType<double>` as in the example and this is a supported type as seen here [(inline AtomicType<double>::AtomicType())](https://github.com/BlueBrain/HighFive/blob/00dad7172c2163c96448a6e5d7a882af72e1b2b4/include/highfive/bits/H5DataType_misc.hpp#L136)

**To Reproduce**
Just run the example compound_types.cpp.

**Expected behavior**

**Stacktrace**
```
In file included from /u/wk/cdegrend/usr/local/include/highfive/bits/../H5DataType.hpp:395,
                 from /u/wk/cdegrend/usr/local/include/highfive/bits/../H5Attribute.hpp:15,
                 from /u/wk/cdegrend/usr/local/include/highfive/bits/H5Annotate_traits.hpp:14,
                 from /u/wk/cdegrend/usr/local/include/highfive/H5File.hpp:16,
                 from test.cpp:1:
/u/wk/cdegrend/usr/local/include/highfive/bits/../bits/H5DataType_misc.hpp: In instantiation of ‘HighFive::AtomicType<T>::AtomicType() [with T = Size2D]’:
/u/wk/cdegrend/usr/local/include/highfive/bits/../bits/H5DataType_misc.hpp:433:12:   required from ‘HighFive::DataType HighFive::create_datatype() [with T = Size2D]’
/u/wk/cdegrend/usr/local/include/highfive/bits/../bits/H5DataType_misc.hpp:441:36:   required from ‘HighFive::DataType HighFive::create_and_check_datatype() [with T = Size2D]’
/u/wk/cdegrend/usr/local/include/highfive/bits/H5Node_traits_misc.hpp:77:77:   required from ‘HighFive::DataSet HighFive::NodeTraits<Derivate>::createDataSet(const string&, const T&, const DataSetCreateProps&, const DataSetAccessProps&, bool) [with T = std::vector<Size2D>; Derivate = HighFive::File; std::string = std::__cxx11::basic_string<char>; HighFive::DataSetCreateProps = HighFive::PropertyList<HighFive::PropertyType::DATASET_CREATE>; HighFive::DataSetAccessProps = HighFive::PropertyList<HighFive::PropertyType::DATASET_ACCESS>]’
test.cpp:27:57:   required from here
/u/wk/cdegrend/usr/local/include/highfive/bits/../bits/H5DataType_misc.hpp:189:57: error: static assertion failed: Type not supported
  189 |     static_assert(details::inspector<T>::recursive_ndim > 0, "Type not supported");
```
**Desktop (please complete the following information):**
 - OS: Red Hat Enterprise Linux Workstation
 - Version master branch
 
Thanks for any insight!

**Comment by alkino** [comment] 2022-04-07 06:32
I'm sorry, but it works for me.
Can you try with the last version?

Or otherwise give us a backtrace?

**Comment by alkino** [comment] 2022-06-28 13:56
I'm closing this as we changed the type system and we didn't reproduce the problem. If you are still facing it, feel free to open again this issue.

**Closed** 2022-06-28 13:56 UTC
