### ISSUE TITLE
`Parallel hdf5` example compilation gives error with `GCC 13.1.0` but not with `GCC-8.1.0`

### ISSUE THREAD

**Issue by dutta-alankar** [BlueBrain/HighFive#752] opened 2023-05-12 05:51 UTC
I was trying to compile `parallel_hdf5_independent_io.cpp` from the example using
```
 mpic++ parallel_hdf5_independent_io.cpp -I/home/alankar/HighFive/include -I/modules/comp_libs/hdf5/parallel/include -L/modules/comp_libs/hdf5/parallel/lib -lhdf5 -o parallel_hdf5_independent_io
```
Here `mpicc` is from `mpich` and this gives error with `GCC 13.1.0` but works fine with `GCC 8.1.0`.

**Error message**:
```
In file included from /modules/compilers/gcc1310/include/c++/13.1.0/bits/move.h(57),
                 from /modules/compilers/gcc1310/include/c++/13.1.0/bits/exception_ptr.h(41),
                 from /modules/compilers/gcc1310/include/c++/13.1.0/exception(164),
                 from /modules/compilers/gcc1310/include/c++/13.1.0/ios(41),
                 from /modules/compilers/gcc1310/include/c++/13.1.0/ostream(40),
                 from /modules/compilers/gcc1310/include/c++/13.1.0/iostream(41),
                 from parallel_hdf5_independent_io.cpp(10):
/modules/compilers/gcc1310/include/c++/13.1.0/type_traits(3363): error: type name is not allowed
    inline constexpr bool is_convertible_v = __is_convertible(_From, _To);
                                                              ^
```

**Desktop (please complete the following information):**
 - OS: CentOs 7
 - Version 2.7.1 release

**Comment by 1uc** [comment] 2023-05-14 11:04
I can't reproduce it with GCC 13.1.1 and OpenMPI. Which, is unfortunately both a bug release later and a different version of MPI.

There's this which sounds related:
https://forums.developer.nvidia.com/t/strange-errors-after-system-gcc-upgraded-to-13-1-1/252441

Installing GCC 13.1.0 from Spack isn't sufficient to reproduce the issue. A quick check to see if it's picking up the right STL libraries suggests it is:
```
echo '#include <type_traits>' | mpic++ -x c++ -E - | grep '/type_traits"'
# 1 "${HOME}/git/spack/opt/spack/linux-arch-icelake/gcc-13.1.1/gcc-13.1.0-4boeihdngyw33sqq3uxy4ucbzwhwzzlp/lib/gcc/x86_64-pc-linux-gnu/13.1.0/../../../../include/c++/13.1.0/type_traits" 1 3
```

I'm also unable to reproduce with MPICH (GCC 13.1.0 and GCC 13.1.1).

**Comment by dutta-alankar** [comment] 2023-05-14 11:23
I'm at a loss. @1uc Can you suggest to me what more info I can provide so that you may be able to reproduce this issue?

**Comment by 1uc** [comment] 2023-05-14 15:26
@dutta-alankar I don't really know. Probably, the first thing would be to make the problem simpler. I sounds like it shouldn't depend on MPICH or MPI in general. In fact we should be able to reduce it to something not even HighFive related. What happens if you compile some other example with `g++` (version 13.1.0)?

For example,
[create_dataset_double.cpp](https://github.com/BlueBrain/HighFive/blob/master/src/examples/create_dataset_double.cpp)
[read_write_vector_dataset_references.cpp](https://github.com/BlueBrain/HighFive/blob/master/src/examples/read_write_vector_dataset_references.cpp)

If both work, could you please paste the entire error message emitted by GCC 13.1.0? Usually there's some hint as to which line is the root cause. From the snippet you posted I can only see that it's because we include `<iostream>`.

Finally, sometimes avoiding the issue is the preferred choice: Can you use GCC 8.1.0? If not, can you try GCC 13.1.0 with `--std=c++14` or maybe `--std=c++20`. Can you update to GCC 13.1.1? Could you use Spack to obtain a different version of GCC?

**Comment by 1uc** [comment] 2023-05-17 21:05
I'm really not sure I can help you with this issue. The link errors you're seeing now seem to suggest that something's not right with your compiler/linker.

There's two commands we can try, in the hope they'll show something strange:
```
$ echo '#include <type_traits>' | mpic++ -x c++ -E - | grep '/type_traits"'
# 1 "/usr/include/c++/13.1.1/type_traits" 1 3
...
```
I think what this does is preprocess a C++ file containing only the line `#include<type_traits>`. Conveniently, the output shows which file is included, i.e. `/usr/include/c++/13.1.1/type_traits` in my case. Which makes sense since that's the compiler I'm using. If things are setup correctly you should see headers for version `13.1.0`. With luck you'll see that this isn't actually the case; luck because then you know what to fix.

When I search for `undefined reference std::__throw_bad_array_new_length()` I found this discussion:
https://gcc.gnu.org/pipermail/gcc-help/2021-June/140496.html

Essentially what was happening was that somehow the wrong version of `libstdc++.so` was being used. The concern being that in your case `g++` is picking up the wrong version of the standard library. For example the one from GCC 8.1.0. The post has commands to check this type of thing, i.e. add `-Wl,--trace`. Full command should be:
```
g++ create_dataset_double.cpp -o create_dataset_double -lhdf5 -I/home/alankar/idefix/src/HighFive/include -Wl,--trace
```
In my case it outputs:
```
...
/usr/lib/gcc/x86_64-pc-linux-gnu/13.1.1/../../../../lib/libstdc++.so
...
```
which show that it's using the version I'd like it to. 

What's odd about the errors is that they would be related to HighFive. With those errors it should be hard to compile even rather simple C++ files. Does GCC 13.1.0 otherwise work flawlessly? The mentioned discussion has the following reproducer, does it compile? Does it compile (and link) if you pointlessly also link to HDF5, i.e. `-lhdf5`?

```
struct Thing { int a, b, c; };
int main(int argc, char **argv) {
    std::unordered_map<unsigned int, Thing *> map;
    map[1] = new Thing;
}
```

**Comment by dutta-alankar** [comment] 2023-05-19 18:45
@1uc As you suggested, the first thing I did was clean my environment and then I did the following.
- This is what I get from the first command you shared. Seems like the compiler and headers are consistent.
```
alankar@chandra:~/HighFive/src/examples$ echo '#include <type_traits>' | mpic++ -x c++ -E - | grep '/type_traits"'
# 1 "/modules/compilers/gcc1310/include/c++/13.1.0/type_traits" 1 3
# 33 "/modules/compilers/gcc1310/include/c++/13.1.0/type_traits" 3
# 39 "/modules/compilers/gcc1310/include/c++/13.1.0/type_traits" 2 3
# 437 "/modules/compilers/gcc1310/include/c++/13.1.0/type_traits" 3
# 733 "/modules/compilers/gcc1310/include/c++/13.1.0/type_traits" 3
# 753 "/modules/compilers/gcc1310/include/c++/13.1.0/type_traits" 3
# 1407 "/modules/compilers/gcc1310/include/c++/13.1.0/type_traits" 3
# 1420 "/modules/compilers/gcc1310/include/c++/13.1.0/type_traits" 3
# 1518 "/modules/compilers/gcc1310/include/c++/13.1.0/type_traits" 3
# 1739 "/modules/compilers/gcc1310/include/c++/13.1.0/type_traits" 3
# 1814 "/modules/compilers/gcc1310/include/c++/13.1.0/type_traits" 3
# 1899 "/modules/compilers/gcc1310/include/c++/13.1.0/type_traits" 3
# 1946 "/modules/compilers/gcc1310/include/c++/13.1.0/type_traits" 3
# 2282 "/modules/compilers/gcc1310/include/c++/13.1.0/type_traits" 3
# 2658 "/modules/compilers/gcc1310/include/c++/13.1.0/type_traits" 3
# 2700 "/modules/compilers/gcc1310/include/c++/13.1.0/type_traits" 3
# 3360 "/modules/compilers/gcc1310/include/c++/13.1.0/type_traits" 3
# 3825 "/modules/compilers/gcc1310/include/c++/13.1.0/type_traits" 3
```

Next, I test the other command you shared and this works with serial:
```
alankar@chandra:~/HighFive/src/examples$ g++ create_dataset_double.cpp -o create_dataset_double -lhdf5 -I/home/alankar/HighFive/include -Wl,--trace
/lib/../lib64/crt1.o
/lib/../lib64/crti.o
/modules/compilers/gcc1310/lib/gcc/x86_64-pc-linux-gnu/13.1.0/crtbegin.o
/tmp/ccM9vovq.o
/modules/comp_libs/hdf5/serial/lib/libhdf5.so
/modules/compilers/gcc1310/lib/gcc/x86_64-pc-linux-gnu/13.1.0/../../../../lib64/libstdc++.so
/lib/../lib64/libm.so
/modules/compilers/gcc1310/lib/gcc/x86_64-pc-linux-gnu/13.1.0/../../../../lib64/libgcc_s.so
/modules/compilers/gcc1310/lib/gcc/x86_64-pc-linux-gnu/13.1.0/../../../../lib64/libgcc_s.so.1
/modules/compilers/gcc1310/lib/gcc/x86_64-pc-linux-gnu/13.1.0/libgcc.a
/modules/compilers/gcc1310/lib/gcc/x86_64-pc-linux-gnu/13.1.0/libgcc.a
/modules/compilers/gcc1310/lib/gcc/x86_64-pc-linux-gnu/13.1.0/libgcc.a
/lib/../lib64/libc.so
/lib64/libc.so.6
/usr/lib64/libc_nonshared.a
/lib64/ld-linux-x86-64.so.2
/usr/lib64/libc_nonshared.a
/lib64/ld-linux-x86-64.so.2
/modules/compilers/gcc1310/lib/gcc/x86_64-pc-linux-gnu/13.1.0/../../../../lib64/libgcc_s.so
/modules/compilers/gcc1310/lib/gcc/x86_64-pc-linux-gnu/13.1.0/../../../../lib64/libgcc_s.so.1
/modules/compilers/gcc1310/lib/gcc/x86_64-pc-linux-gnu/13.1.0/libgcc.a
/modules/compilers/gcc1310/lib/gcc/x86_64-pc-linux-gnu/13.1.0/libgcc.a
/modules/compilers/gcc1310/lib/gcc/x86_64-pc-linux-gnu/13.1.0/crtend.o
/lib/../lib64/crtn.o
```
 - Here's what I get with parallel hdf5 and this fails.:
```
alankar@chandra:~/HighFive/src/examples$ mpic++ parallel_hdf5_collective_io.cpp -o parallel_hdf5_collective_io -lhdf5 -I/home/alankar/HighFive/include -Wl,--trace
In file included from /modules/compilers/gcc1310/include/c++/13.1.0/bits/move.h(57),
                 from /modules/compilers/gcc1310/include/c++/13.1.0/bits/exception_ptr.h(41),
                 from /modules/compilers/gcc1310/include/c++/13.1.0/exception(164),
                 from /modules/compilers/gcc1310/include/c++/13.1.0/ios(41),
                 from /modules/compilers/gcc1310/include/c++/13.1.0/ostream(40),
                 from /modules/compilers/gcc1310/include/c++/13.1.0/iostream(41),
                 from parallel_hdf5_collective_io.cpp(10):
/modules/compilers/gcc1310/include/c++/13.1.0/type_traits(3363): error: type name is not allowed
    inline constexpr bool is_convertible_v = __is_convertible(_From, _To);
                                                              ^

In file included from /modules/compilers/gcc1310/include/c++/13.1.0/bits/move.h(57),
                 from /modules/compilers/gcc1310/include/c++/13.1.0/bits/exception_ptr.h(41),
                 from /modules/compilers/gcc1310/include/c++/13.1.0/exception(164),
                 from /modules/compilers/gcc1310/include/c++/13.1.0/ios(41),
                 from /modules/compilers/gcc1310/include/c++/13.1.0/ostream(40),
                 from /modules/compilers/gcc1310/include/c++/13.1.0/iostream(41),
                 from parallel_hdf5_collective_io.cpp(10):
/modules/compilers/gcc1310/include/c++/13.1.0/type_traits(3363): error: type name is not allowed
    inline constexpr bool is_convertible_v = __is_convertible(_From, _To);
                                                                     ^

In file included from /modules/compilers/gcc1310/include/c++/13.1.0/bits/move.h(57),
                 from /modules/compilers/gcc1310/include/c++/13.1.0/bits/exception_ptr.h(41),
                 from /modules/compilers/gcc1310/include/c++/13.1.0/exception(164),
                 from /modules/compilers/gcc1310/include/c++/13.1.0/ios(41),
                 from /modules/compilers/gcc1310/include/c++/13.1.0/ostream(40),
                 from /modules/compilers/gcc1310/include/c++/13.1.0/iostream(41),
                 from parallel_hdf5_collective_io.cpp(10):
/modules/compilers/gcc1310/include/c++/13.1.0/type_traits(3363): error: identifier "__is_convertible" is undefined
    inline constexpr bool is_convertible_v = __is_convertible(_From, _To);
                                             ^

parallel_hdf5_collective_io.cpp(121): warning #2196: routine is both "inline" and "noinline"

compilation aborted for parallel_hdf5_collective_io.cpp (code 2)
```

I also faced no issues compiling the following code with and also without the dummy `-lhdf5` flag.
```c++
#include <iostream>
#include <unordered_map>

struct Thing { int a, b, c; };
int main(int argc, char **argv) {
    std::unordered_map<unsigned int, Thing *> map;
    map[1] = new Thing;
    return 0;
}
```

As a side note, I was trying the `Kokkos`  C++ library where I get a similar error message and they explicitly mention that their current `Kokkos` library is incompatible with `gcc^13.1.0`.

**Comment by dutta-alankar** [comment] 2023-05-24 09:15
Thanks for taking time to review this. It then seems to be an incompatibility in versions of mpich and hdf5. You may close this issue.

**Comment by 1uc** [comment] 2023-05-25 18:29
Likewise, and thanks for reporting it.

I think even though it's not resolved, I'd like to close this. If others encounter a similar issue, please open a new ticket, since that will make it easier to keep track of the context of each bug report.

**Closed by 1uc** 2023-05-25 18:29 UTC
