### ISSUE TITLE
H5Converter_misc: "Booleans are not supported yet" error & H5ReadWrite_misc "used but never defined" error

### ISSUE THREAD

**Issue by yyu233** [BlueBrain/HighFive#607] opened 2022-09-07 01:02 UTC
**To Reproduce**
1. Build docker image from this docker file:[bioslam](https://github.com/tmcg0/bioslam/blob/dev/docker/Dockerfile#L63-L65)

**Expected behavior**
No error

**Stacktrace**
```
#37 5.598 /usr/local/include/highfive/bits/H5Converter_misc.hpp:83:19: error: static assertion failed: Booleans are not supported yet.
#37 5.598    83 |     static_assert(!std::is_same<type, bool>::value, "Booleans are not supported yet.");
#37 5.598       |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
```
#37 9.074 /usr/local/include/highfive/bits/H5ReadWrite_misc.hpp:106:1: error: 'HighFive::details::BufferInfo<T>::BufferInfo(const HighFive::DataType&, F) [with F = HighFive::SliceTraits<Derivate>::write(const T&) [with T = bool; Derivate = HighFive::DataSet]::<lambda()>; T = bool]', declared using local type 'HighFive::SliceTraits<Derivate>::write(const T&) [with T = bool; Derivate = HighFive::DataSet]::<lambda()>', is used but never defined [-fpermissive]
#37 9.074   106 | BufferInfo<T>::BufferInfo(const DataType& dtype, F getName)
#37 9.074       | ^~~~~~~~~~~~~
```

**Desktop (please complete the following information):**
 - OS:  Ubuntu
 - Version: `Linux gnocchi 5.15.0-46-generic #49~20.04.1-Ubuntu`

**Comment by alkino** [comment] 2022-09-14 11:20
See #25 and #490

I had hard time trying to add a full support of boolean. Because everything is broken in HighFive :p

**Comment by ohm314** [comment] 2022-09-14 14:38
To be more precise: Not everything is broken in HighFive but `vector<bool>` type is not (yet) the reason being their internal representation in stdlib. I'm going to close this since it is essentially a duplicate of previous issues.

**Closed by ohm314** 2022-09-14 14:38 UTC
