### ISSUE TITLE
dataset.read() After reading the data, will it hold the data and cannot release it?

### ISSUE THREAD

**Issue by WanXinTao** [BlueBrain/HighFive#449] opened 2021-04-29 08:05 UTC
I encountered this situation in the code below. After holding the data, it cannot be released and it takes up memory.

```
HighFive::File file(file_path, HighFive::File::ReadOnly);
HighFive::DataSet dataset = file.getDataSet(dataset_name);
HighFive::DataSpace space = dataset.getSpace();

int dims = space.getNumberDimensions();
auto res = std::make_shared<std::vector<std::string>>();
if (dims == 0) {
      std::string result;
      dataset.read(result);
      res->push_back(std::move(result));
} else {
      dataset.read(*res);
}
return res;
```

**Comment by WanXinTao** [comment] 2021-04-30 00:24
I mean the memory cannot be released after getting the data
@ohm314

**Comment by WanXinTao** [comment] 2021-04-30 00:26
When I get the data through the above method, although the function exits, but the memory cannot be released

**Comment by ohm314** [comment] 2021-04-30 09:15
Can you please provide a full reproducer and specify which memory (associated to which variable) is not released and how you come to the conclusion that the memory is not released? With the current information I don't quite see the issue, sorry.

**Comment by WanXinTao** [comment] 2021-04-30 10:19
![image](https://user-images.githubusercontent.com/21972225/116682117-6b209d00-a9e0-11eb-9aff-cb71ca209a4a.png)
![image](https://user-images.githubusercontent.com/21972225/116682176-7d024000-a9e0-11eb-9069-767600100c17.png)
![image](https://user-images.githubusercontent.com/21972225/116682225-8e4b4c80-a9e0-11eb-9518-17865f9d7678.png)
![image](https://user-images.githubusercontent.com/21972225/116682265-9e632c00-a9e0-11eb-8549-db3ad1eeaea8.png)

**Comment by WanXinTao** [comment] 2021-04-30 10:21
@ohm314 
I wrote a demo, described as the logic of the problem code, and the other thing I don’t understand is why there is a piece of memory that can’t be released.

**Comment by matz-e** [comment] 2021-04-30 11:46
@WanXinTao I'm not sure if we can help much here. I've adapted your reproducer to one of the HDF5 files with strings we have, and I see memory allocated drop from >1 GB to much less.

IIRC, memory behavior may vary a bit, see this blog post from the interwebs: https://lemire.me/blog/2020/03/03/calling-free-or-delete/

**Comment by WanXinTao** [comment] 2021-04-30 12:25
Can you show me your code
@matz-e

**Comment by WanXinTao** [comment] 2021-04-30 12:26
I am a server service. After loading the data, I can see from the monitoring that the memory has been continuously 1.7G
@matz-e

**Comment by matz-e** [comment] 2021-04-30 12:32
See [here](https://gist.github.com/matz-e/d5b958ba186957a208096db78ff037b1).

**Comment by WanXinTao** [comment] 2021-04-30 12:47
Sorry, I can't open this URL.
Can you send me the code picture
@matz-e

**Comment by matz-e** [comment] 2021-04-30 13:05
Seems weird…
![image](https://user-images.githubusercontent.com/2151261/116698928-410db180-a9c5-11eb-91f3-610d1dffd0ec.png)

But is this also not expected behavior? You fragment the memory space, and the OS may delay re-using the memory pages, showing a seemingly constant memory consumption. Do you observe an actual memory leak here over longer time frames?

**Comment by WanXinTao** [comment] 2021-04-30 13:35
I have been observing for 2 days, the memory has been 1.7G
What is the size of the data in your demo? Didn't your demo reappear?
@matz-e

**Comment by matz-e** [comment] 2021-04-30 13:50
About 1.2-1.3G. And I'm not sure what you mean by "Didn't your demo reappear"

**Comment by WanXinTao** [comment] 2021-04-30 13:53
What I mean is whether the memory is significantly reduced after loading the object and destroying the object

**Comment by matz-e** [comment] 2021-04-30 14:08
Yes, my memory drops with the example just like that.

But if I do the following instead:
```
int
main()
{
    std::cout << "Schdard\n";
    std::vector<double> nummern;
    {
        auto _ = read();
        std::cout << "Mer häm " << _->size() << " schdrings g'läse\n";
        sleep(10);
        nummern.resize(100000000);
        nummern[123456789] = 5;
        std::cout << "I hab d'ebbes g'sätzt\n";
        sleep(10);
    }
    std::cout << "Färdisch\n";
    sleep(1000);
    return 666;
}
```

Where I allocate a large vector after reading from HDF5, I see my memory going from basically 0 to 1.2G, then after the reserve to 1.7G where it stays.

Again, this seems to be expected behavior. Them OS assigns my process the required memory, and I use all of it to allocate HDF5 data and my numbers. After I discard the HDF5 data, I have part of the memory occupied by the other vector and re-assigning that to other programs will fragment the memory space heavily over time?

**Comment by WanXinTao** [comment] 2021-04-30 14:25
At present, the memory of my program is constant at 1.7G for 2 days
Are we using the same highfive version?
@matz-e

**Comment by WanXinTao** [comment] 2021-05-01 11:54
@ohm314 
I want to get some help to solve the problem I am facing now

**Comment by ohm314** [comment] 2021-05-02 22:13
@WanXinTao, I don't think `top` is giving you an accurate measurement of your memory usage. I am not convinced there is an issue in HDF5 or HighFive but what you are seeing is simply an artifact of how linux memory management works and how the kernel reports process memory usage. See [here](https://elinux.org/Runtime_Memory_Measurement) for example. To get a precise measurement of heap allocation and possible memory leaks, you would need to use a memory debugger. There are several options (e.g. valgrind) that can help you to check this out, if you are really sure there is a problem in HighFive's code. If you find something concrete, we'd be more than glad to assist you in fixing it.

**Comment by alkino** [comment] 2021-08-28 05:03
I close it after this last answer.
Feel free to open it again.

**Closed by alkino** 2021-08-28 05:03 UTC
