### ISSUE TITLE
Why header-only?

### ISSUE THREAD

**Issue by emmenlau** [BlueBrain/HighFive#170] opened 2019-03-08 14:18 UTC
Thanks for the very nice HighFive library, its highly appreciated!

Please allow a humble question: Why was the library designed to be header-only? When browsing the code I was under the impression that there are quite a number of non-template-classes that would equally well or better be suited for compiled object code?

I think header-only definitions make it quite easy to break the https://en.wikipedia.org/wiki/One_Definition_Rule. Specifically exceptions can lead to problems when they are fully inlined because they may be instantiated in different dso's which may lead to failures in looking up the id. We've head troubles with this in the past, up to the point that catching an exception by the specific type would not work when the exception was thrown from a library.

Do you see a strong benefit of heaving the library header-only?

**Comment by ferdonline** [comment] 2019-07-08 11:34
Hi @emmenlau.
As I'm not the original author, my best understanding is that it is so by design to meet one of the main promises: zero overhead library. We expect that the compiler can inline as much as possible so that client code will end up making calls to libhdf5.
Of course that might not be always possible and some errors might stem from that, but it is something we have to be prepared to live with and we try to improve. 
Unfortunately some of members are no longer part of the project, so only a couple of developers can contribute now and then.
Since we don't expect the design to change, I'm closing the issue.
Thanks for the contributions.

**Closed by ferdonline** 2019-07-08 11:34 UTC

**Comment by eschnett** [comment] 2019-07-08 11:45
The main reason why people like header-only libraries is that the installation process is much simplified. There is no need to build and install a library, and to ensure that the library found at link time is the same that was found at compile time. Instead, it suffices to point the compiler to the library via the "-I" flag. Alternatively, you just add a copy of the library to a project, and there is no need to update compile rules.

It is "well known" how to avoid violating the ODR. However, this can be tedious at times, and contributions from beginners might be wrong in this respect.

**Comment by emmenlau** [comment] 2019-07-08 12:05
Dear @ferdonline , thanks for the reply and for outlining the motivation!

I can see the reasoning, but I'm under the impression that the current design brings significant problems for comparably few gains. HighFive is currently throwing custom exceptions which are fully inlined. When it is included in multiple shared libraries, an application will fail to correctly identify the exceptions! The solution can be to use HighFive exclusively from a single shared library, or exclusively from other header-only libraries. However this very much limits the applicability of HighFive.

On the other hand, the the benefit of faster runtime from method inlining is quite marginal when compared to disk access times. And the benefit of simplified installation is probably negligible for most applications because cmake makes the build quite easy on most platforms.

I think HighFive could profit a lot from a design change in this respect. I could offer to make a PR for this change if it can be considered for upstream integration?
