### ISSUE TITLE
select rows

### ISSUE THREAD

**Issue by KerimMatlab** [BlueBrain/HighFive#328] opened 2020-04-16 19:02 UTC
Hi,

I just started using HighFive and I'm really enjoy it! thank all of those who work on it

I found 3 way to select data to read/write:
1) select points (ElementSet)
2) set offset and read number of rows and colums
3) select columns

So why there is select columns but there is no select rows?
Is that because HDF5 is row oriented data format and reading rows is fast enough and it may be accomplished by setting offset and count (of row and col)  ? In the same time reading columns is slower and some improved algorithms are used?

Best regards,
Kerim

**Comment by tdegeus** [comment] 2020-04-21 07:26
Maybe this example could be helpful? https://github.com/BlueBrain/HighFive/blob/master/src/examples/select_partial_dataset_cpp11.cpp

**Comment by KerimMatlab** [comment] 2020-04-21 18:18
@tdegeus thank for reply.
Of course I saw thisexample but it doesn't solve the problem.

I try to explain the question once again.
Create dataset:
`std::vector<size_t> dims = {100, 100};`
`DataSet dataset= group.createDataSet<float>("data", DataSpace(dims));`

Then we can select special columns like 3rd, 20th, 70th, 95th. To do so we write:
`std::vector<size_t> cols = {3, 20, 70, 95};`
`dataset.select(cols);`

But if want to select rows we need to perform loop and make offset for each row:
`std::vector<size_t> rows = {3, 20, 70, 95};`
`for (int i = 0; i < rows.size; i++){`
`    dataset.select({rows(i), 0}, {1, dims(2)}); // here we make offset for each row`
`}`

Why there is no select-row option like we have for select-columns?

**Comment by alkino** [comment] 2020-06-03 12:26
The problem is that the HyperSlab in HDF5 are really powerfull, I don't see an easy way to give access to such a complexity easily.
We cannot add functions for all cases, we should find a generic way to do.

**Comment by KerimMatlab** [comment] 2020-06-03 14:19
@alkino If I understood you correct then the problem is that it is difficult to find convenient syntaxis to wrap `hdf5` hyperslab manipulation and at the same time cover much of hyperslab functionality?
If so I would recommend [Armadillo syntaxes ](http://arma.sourceforge.net/docs.html#syntax)
On link above try to find **Examples of Matlab/Octave syntax and conceptually corresponding Armadillo syntax** topic.
As for me it is unconvenient to extract data by setting `offset` and `size` of extracted dataset

**Comment by alkino** [comment] 2020-06-05 07:13
The problem @KerimMatlab is that **Armadillo** seems to work at most with 2 dimensions. HDF5 has no limit on that.

**Comment by alkino** [comment] 2020-06-08 10:28
I close it with #305

**Closed by alkino** 2020-06-08 10:28 UTC
Labels: enhancement
