### ISSUE TITLE
How to speed up write large hdf5 file [with lots of group and each group is not large].

### ISSUE THREAD

**Issue by wystephen** [BlueBrain/HighFive#682] opened 2023-02-04 13:36 UTC
**Is your feature request related to a problem? Please describe.**
I need to speed up writing the hdf5 file [ three layers (/method_name/stage_name/property), 10W properties, 10G, costs 30 seconds].
BTW, I save this file to a virtual disk [use RAM], it's speed not improved compare to directly write to a ssd.

**Describe the solution you'd like**
Multi-thread support for writing datasets (single computer, single h5 file).

**Describe alternatives you've considered**

**Additional context**

**Comment by 1uc** [comment] 2023-02-04 14:55
HDF5 doesn't support any form of multi-threaded concurrency (neither reading nor writing). Generally, any concurrent (multi-threaded or multi-process) creation of datasets seems unlikely to be implemented soon (if ever).

You say writing the file to RAM or some SSD takes the same amount of time. This suggests that what's slow isn't related to how the storage medium is accessed. Therefore, the first step would be to figure out if the bottleneck is inside of HighFive or HDF5. There's two options, you can profile your application, or you can create a clone of the application which only uses pure HDF5.

If you know that the issue is inside of HighFive you can update this ticket with the relevant information we need to look into it. Then we can help you figure out why HighFive is slow compared to native HDF5 and what can be done about it.

If you find that the issue persists when using only pure HDF5, you can try reading the upstream documentation. I'd start with anything metadata related:
 * https://docs.hdfgroup.org/hdf5/develop/_t_n_m_d_c.html
 * https://portal.hdfgroup.org/display/HDF5/HDF5+Metadata
 * https://portal.hdfgroup.org/display/HDF5/Fine-tuning+the+Metadata+Cache
 
If that doesn't lead to anything, there's the HDF5 forum which is how you can contact HDF5 experts.

**Comment by wystephen** [comment] 2023-02-05 03:14
> HDF5 doesn't support any form of multi-threaded concurrency (neither reading nor writing). Generally, any concurrent (multi-threaded or multi-process) creation of datasets seems unlikely to be implemented soon (if ever).
> 
> You say writing the file to RAM or some SSD takes the same amount of time. This suggests that what's slow isn't related to how the storage medium is accessed. Therefore, the first step would be to figure out if the bottleneck is inside of HighFive or HDF5. There's two options, you can profile your application, or you can create a clone of the application which only uses pure HDF5.
> 
> If you know that the issue is inside of HighFive you can update this ticket with the relevant information we need to look into it. Then we can help you figure out why HighFive is slow compared to native HDF5 and what can be done about it.
> 
> If you find that the issue persists when using only pure HDF5, you can try reading the upstream documentation. I'd start with anything metadata related:
> 
> * https://docs.hdfgroup.org/hdf5/develop/_t_n_m_d_c.html
> * https://portal.hdfgroup.org/display/HDF5/HDF5+Metadata
> * https://portal.hdfgroup.org/display/HDF5/Fine-tuning+the+Metadata+Cache
> 
> If that doesn't lead to anything, there's the HDF5 forum which is how you can contact HDF5 experts.

The reason causes slow writing file is create too much groups .

**Comment by alkino** [comment] 2023-02-15 14:22
If the reason of slowdown is creation of too much groups, this problem rely on HDF5 directly.

So I close this ticket. If you find bug on the side of HighFive, feel free to reopen.

**Closed by alkino** 2023-02-15 14:22 UTC
