### ISSUE TITLE
HDF5 1.10.6 error

### ISSUE THREAD

**Issue by nyckmaia** [BlueBrain/HighFive#290] opened 2020-02-19 17:02 UTC
Hi,

My app is working perfectly using HDF5 library `1.10.5`, but when I switch to link it with the **updated** version `1.10.6`, it crashes in this line below: 

```
_outputFile = new H5Easy::File(fileName, H5Easy::File::Overwrite);
```

![image](https://user-images.githubusercontent.com/4555404/74855460-7fb6cf00-531f-11ea-9932-cc21b45740ea.png)

Do you have any ideas?

**My setup:**
 * Windows 10 x64
 * MSVC 2019

**Comment by tdegeus** [comment] 2020-02-20 07:50
Could you try to prepare a minimal code that gives this error?

**Comment by nyckmaia** [comment] 2020-02-20 12:37
Sorry, my fault...

I forget to build the HighFive Library again with the updated version of HDF5 library.

I will try it...

**Comment by alkino** [comment] 2020-02-27 21:26
I think, it works? In 3 days I close this issue, because I cannot reproduce.

**Comment by nyckmaia** [comment] 2020-02-28 12:52
Thank you @alkino for your attention...
In this week I was far from my PC...so I will test this issue only in the middle of the next week.

I think that will be all good when I build the HighFive Library again with the updated HDF5 library.

I will close this issue!

**Closed** 2020-02-28 12:53 UTC

**Comment by alkino** [comment] 2020-02-28 12:54
Thank you for the report but yes I think you have ABI uncompatibility due to the mismatch of the versions.
