### ISSUE TITLE
dataset issue

### ISSUE THREAD

**Issue by Russelleq** [BlueBrain/HighFive#260] opened 2019-12-11 18:26 UTC
Please pardon my ignorance. Suppose you have two datasets in a hdf5 file, would there be any way to open it in a manner stated below? Is there any way to delete the property given to the word "dataset" and use it again to define the second dataset? 

```c++
      HighFive::DataSet dataset=file.getDataSet("/Boundary/Patch->area");                            
      std::vector<double> bou_patchA;                                                                
      dataset.read(bou_patchA);                                                                      
                                                     
      HighFive::DataSet dataset=file.getDataSet("/Boundary/bnd_qua->elem");                          
      std::vector<int> bou_bqelem;                                                                   
      dataset.read(bou_bqelem);                                                                      
```

**Comment by tdegeus** [comment] 2019-12-11 21:17
This question appears to be unrelated to HighFive. The problem is that you are reallocating an existing variable. You could simply not do that:
```cpp
HighFive::DataSet dataset=file.getDataSet("/Boundary/Patch->area");                            
std::vector<double> bou_patchA;                                                                
dataset.read(bou_patchA);                                                                      
                                                 
dataset=file.getDataSet("/Boundary/bnd_qua->elem");                          
std::vector<int> bou_bqelem;                                                                   
dataset.read(bou_bqelem);  
```

You can also let the variable `dataset` go out of scope. It is then freed and can be allocated again:
```cpp
std::vector<double> bou_patchA;                                                                
std::vector<int> bou_bqelem;     

{
    HighFive::DataSet dataset=file.getDataSet("/Boundary/Patch->area");                            
    dataset.read(bou_patchA);                                                                      
}
                 
{                                
    HighFive::DataSet dataset=file.getDataSet("/Boundary/bnd_qua->elem");                                                                                    
    dataset.read(bou_bqelem);  
}
```

Note: take care not to let your `std::vector`s go out-of-scope, as they would stop to exist.

**Closed** 2019-12-12 08:00 UTC
